#+TITLE:  Automatically Update Repo using Github Actions #5
#+AUTHOR: Zach Mandeville

* The Ticket
  Whenever we want to update the json within resources/coverage, it requires running a set of psql commands. This could be automated, which would mean apisnoop the site stays up to date with minimal manual work needed.

Look into github actions for doing this. ATtfirst, it would be good to update it every day. Later, we could update it based on a style of commit to kubernetes/kubernetes (e.g. every time a commit is made to the conformance.yaml file, or that has a 'conformance' label).
* The Process
** Create a .github/workflows directory
   I created this from the github ui, by clicking actions and 'make your own workflow'.  This created the folder ~.github/workflow~ with the file ~main.yaml~
   We'll adjust this file to start up our postgres container and then run a psql command to verify its working.
** Setup job using our snoopdb as the postgres container

** Find the right service contaioner that has psql on it
** Setup up job that runs our `generate_coverage_json.sql` command
** test and iterate
