#+TITLE: 10: Progress on Technical Debt 
#+AUTHOR: Zach Mandeville
#+TODO: TODO NEXT IN-PROGRESS | DONE

* The Ticket
  Both 'Stable Coverage At Time of Release' graphs should explicitly show the work done to reduce technical debt. This is defined as new tests written for old endpoints.

On the graphs currently, tested shows as green and untested shows as red. When a new endpoint comes in with a test it is shown as light green, and a new endpoint without a test a light yellow.

In addition, show tech debt progress with a different shade of green.

While we're at it, let's switch the name of each of the keys to be a bit more readable.  new_untested and new_with_tests just doesn't look good as a legend.
* The Strategy
** DONE Determine whether we need to change json to get info we need
   CLOSED: [2020-07-27 Mon 16:10]
   We need to add 'old_tested' to it, but otherwise unchanged.
   While i was there, i updated it to pretty print the json so it'd look a bit nicer when viewing it as just a file in the repo.
** Change the name of the keys in current graphs
   I've renamed these to be explicit and concise:
   - New Endpoints Promoted with Tests
   - New Endpoints Promoted Without Tests
   - Old Endpoints Covered by New Tests
   - Tested
   - Untested
   
   While concise, it is still longer than just ~new_tested~ and i found that the legend was cutting off the text.
** Set labelLimit for legend 
   After digging into the vega docs and experimenting with adjusting the orientation and direction of the legend, I found the 'labelLimit' property, which let me increase the max pixel width of each label in the legend.  Now I can keep the legend where it is and have the whole name without truncation.  I am uncertain how good this looks on smaller monitors than a macbook, and so it will be good to check and adjust this.
** Build stack with distinct old endpoints 
   We already had this value being brought over in our coverage json, we were just not doing anything with it.  I added it to the vega chart, adjusting the other values as needed (since we are doing a stacked chart, we need to subtract our variou svalues from our ttotal tested or untested, otherwise the stack goes over the totatl number of endpoints)
** Improve colors on chart using hsl
   The colours previously were hex codes.  I switched all of them to hsl so that the similar colours (e.g. greens) would be easier to spot.  I then made the greens consistent by increasing their lightness by 10% per coverage type.  So the darkest is the tested, then old endpoints now tested, then new endpoints with tests.
** Double check that we want tech debt in percentage chart
   I want to double check, before changing up this chart, whether having it be as indepth ast he top one is really what we want, or if having this info now in the top one is enough.  So i'll push the changes to be able to show the team and then review.  It's possible, but will take a bit of refactoring that I don't want to do if we end up changing it right back.
* Conclusion
  
  
