#+NAME: Coverage Sources is an Array of Sources # 11
#+AUTHOR: Zach Mandeville

*  The Ticket
  For our most recent releases (and possibly all releases) in resources/coverage, we've pulled from multiple data sources, bu7t the output json only shows one. This should be updated to be an array, so the front end can more accurately describe how we've gotten our data.
* The Process
  The coverage json is made with the function generate_coverage_json...so we just need to update that
** Update function [[file:~/snoop/postgres/tables-views-functions.org::*Generate latest coverage json][Generate latest coverage json]]
** update snoopApp view to pull from sources and display as a list.
   I simply adjusted the prologue for the sunburst to show a list of sources, with some logic to have the text say _how_ many sources there are.
* Conclusion
  This was a straightforward exercise.  if we have multiple sources (which we will for all rleases from 1.19 onward) we can display them all above the sunburst.
