#+TITLE: 497_update Releases

* The Ticket
#+begin_quote
Add new release 1.22 to the APISnoop web UI
#+end_quote
[[https://github.com/cncf/apisnoop/issues/497][source]]
* Strategy
I want to fix our releases now, so that updating apisnoop per release is not an opaque, intensive proccess.
Ideally, you would just need to update a releases.yaml file, push a tag with this update, and have our pipeline handle the rest.

At the moment, for each release we need to:
- in snoopdb
  - function: load_open_api
  - bootstrap script: load_all_open_api
- in webapp:
  - update releases in src/lib/constants.js
- in repo:
  - update resources/coverage/releases.yaml

My goal is to make it so you only do the last part.
* Update coverage/releases.yaml
I did this and commited to main to make the resxt of this easier. Instead of it
just being a list of release versions, it is now a list of objects containing
the version and the release date. This makes it so that we no longer have to
update the version dates in the ~load_open_api~ script, which was an
anti-pattern.
* Fix Snoopdb
** Fix load_open_api
Now I should only need to curl our releases.yaml and get the dates and such we need from that, then update the query appropriately.

The new function would look like so:

#+NAME: updated load_open_api
#+begin_src sql-mode
create or replace function load_open_api (
  custom_release text default null
  )
returns text AS $$
from string import Template
import json
import time
import datetime
from urllib.request import urlopen, urlretrieve
import urllib
import yaml

K8S_REPO_URL = 'https://raw.githubusercontent.com/kubernetes/kubernetes/'
OPEN_API_PATH = '/api/openapi-spec/swagger.json'
RELEASES_URL = 'https://raw.githubusercontent.com/cncf/apisnoop/main/resources/coverage/releases.yaml'

# Get info about latest release from our releases.yaml
releases = yaml.safe_load(urlopen(RELEASES_URL))
latest_release = releases[0]

# Set values for sql template  based on if custom_release argument was passed
if custom_release is not None:
  open_api_url = K8S_REPO_URL + 'v' + custom_release  + OPEN_API_PATH
# check to see if we can load this custom_release url
  try:
    open_api = json.loads(urlopen(open_api_url).read().decode('utf-8'))
    release = custom_release
    rd = [r for r in releases if r['version'] == release][0]['release_date']
    release_date = time.mktime(datetime.datetime.strptime(str(rd), "%Y-%m-%d").timetuple())
  except urllib.error.HTTPError as e:
    raise ValueError('http error with', custom_release)
else:
  open_api_url = K8S_REPO_URL + 'master' + OPEN_API_PATH
  open_api = json.loads(urlopen(open_api_url).read().decode('utf-8'))
  release = latest_release['version']
  release_date = time.mktime(datetime.datetime.now().timetuple())
sql = Template("""
   WITH open AS (
     SELECT '${open_api}'::jsonb as api_data
     )
       INSERT INTO open_api(
         release,
         release_date,
         endpoint,
         level,
         category,
         path,
         k8s_group,
         k8s_version,
         k8s_kind,
         k8s_action,
         deprecated,
         description,
         spec
       )
   SELECT
     '${release}' as release,
     to_timestamp(${release_date}) as release_date,
     (d.value ->> 'operationId'::text) as endpoint,
     CASE
       WHEN paths.key ~~ '%alpha%' THEN 'alpha'
       WHEN paths.key ~~ '%beta%' THEN 'beta'
       -- these endpoints are beta, but are not marked as such, yet, in the swagger.json
       WHEN (d.value ->> 'operationId'::text) = any('{"getServiceAccountIssuerOpenIDConfiguration", "getServiceAccountIssuerOpenIDKeyset"}') THEN 'beta'
       ELSE 'stable'
     END AS level,
     split_part((cat_tag.value ->> 0), '_'::text, 1) AS category,
     paths.key AS path,
     ((d.value -> 'x-kubernetes-group-version-kind'::text) ->> 'group'::text) AS k8s_group,
     ((d.value -> 'x-kubernetes-group-version-kind'::text) ->> 'version'::text) AS k8s_version,
     ((d.value -> 'x-kubernetes-group-version-kind'::text) ->> 'kind'::text) AS k8s_kind,
     (d.value ->> 'x-kubernetes-action'::text) AS k8s_action,
     CASE
       WHEN (lower((d.value ->> 'description'::text)) ~~ '%deprecated%'::text) THEN true
       ELSE false
     END AS deprecated,
                 (d.value ->> 'description'::text) AS description,
                 '${open_api_url}' as spec
     FROM
         open
          , jsonb_each((open.api_data -> 'paths'::text)) paths(key, value)
          , jsonb_each(paths.value) d(key, value)
          , jsonb_array_elements((d.value -> 'tags'::text)) cat_tag(value)
    ORDER BY paths.key;
              """).substitute(release = release,
                              release_date = str(release_date),
                              open_api = json.dumps(open_api).replace("'","''"),
                              open_api_url = open_api_url)
try:
  plpy.execute((sql))
  return "{} open api is loaded".format(release)
except Exception as e:
  return "an error occurred: " + str(e) + "\nrelease: " + release
$$ LANGUAGE plpython3u ;
reset role;

comment on function load_open_api is 'loads given release to open_api table.  Pass release (as "X.XX.X") to load specific release, otherwise loads latest';

select 'load_open_api function defined and commented' as "build log";

#+end_src

This same code block is now in our [[file:~/Projects/apisnoop/apps/snoopdb/tables-views-functions.org][tables-views-functions.org]]
** Fix load_all_open_api
The current bootstrap script takes a set of values from 1.current.0 back to 1.5.0.  We want to have this set generated for us from the releases.yaml
*** create helper function "grab_past_releases"
This script takes all releases save the latest, filters out any that don't have an open_api spect (e.g 1.4.0 and earlier) and returns it as a set of values.
#+NAME: grab_past_releases
#+begin_src
create function grab_past_releases ()
returns setof text
language plpython3u as $$

import json
import yaml
from urllib.request import urlopen, urlretrieve

def has_open_api (version):
    major = version.split('.')[1]
    return int(major) >= 5 # open api wasn't established until 1.5.0

RELEASES_URL = 'https://raw.githubusercontent.com/cncf/apisnoop/main/resources/coverage/releases.yaml'
past_releases = yaml.safe_load(urlopen(RELEASES_URL))[1:]
versions_with_openapi = [release["version"] for release in past_releases if has_open_api(release["version"])]
return versions_with_openapi
$$;
#+end_src

I will add this to our functions as well, redoing the order for logical consistency.
*** update load_all_open_api script

** Test it all works
we should tangle from our org file, get the startup scripts we need, and have it load up successfully in the cluster
* Fix WEbapp
* Write Documentation
