#+TITLE: 497_update Releases

* The Ticket
#+begin_quote
Add new release 1.22 to the APISnoop web UI
#+end_quote
[[https://github.com/cncf/apisnoop/issues/497][source]]
* Strategy
I want to fix our releases now, so that updating apisnoop per release is not an opaque, intensive proccess.
Ideally, you would just need to update a releases.yaml file, push a tag with this update, and have our pipeline handle the rest.

At the moment, for each release we need to:
- in snoopdb
  - function: load_open_api
  - bootstrap script: load_all_open_api
- in webapp:
  - update releases in src/lib/constants.js
- in repo:
  - update resources/coverage/releases.yaml

My goal is to make it so you only do the last part.
* Update coverage/releases.yaml
I did this and commited to main to make the resxt of this easier.  Instead of it just being a list of release versions, it is now a list of objects containing the version and the release date.  This makes it so that we no longer have to update the version dates in the ~load_open_api~ script, which was an anti-pattern.
* Fix Snoopdb
** Fix load_open_api
** Fix load_all_open_api
*** create helper function "grab_past_releases"
*** update load_all_open_api script
** Test it all works
we should tangle from our org file, get the startup scripts we need, and have it load up successfully in the cluster
* Fix WEbapp
* Write Documentation
