#+TITLE: Ticket 80: YASnippet for APISnoop Template Files

* The Ticket
  [[https://gitlab.ii.coop/cncf/apisnoop/issues/80][gitlab link]]

  #+BEGIN_QUOTE
When someone starts up a new ticket org, they should be able to type somethign quick, like tix and have it expand it our ticket structure.  By doing this, we ensure consistency among our ticket reports and save time for our teammates.
  #+END_QUOTE

* Process
** Create a new yasnippet
   The easiest way to do this is with ~SPC SPC yas-new-snippet~
   This will give you its own template to write up.  The name is whatever you'd like to name the snippet, the key is what you'd start to type for yasnippet to find this particular template.
   You can copy and paste an org-mode file directly into the snippet area to save time.
** Save this snippet
   You can save the snippet with ~SPC fs~.  It will auto-set the folder to ~.emacs.d/private/snippets/~ + whatever mode you were in when you started up the snippet (e.g. org-mode).  You can give it a nice name to find later.
   
   If you need to edit the snippet, just find it within your ~.emacs.d/private/snippets/~ folder!
** Test it out
   I tested it out to make this here ticket.  When I'm in org, I can type ~apitix~, which will rpompt a dropdown.  I then hit down to highlight the snippet and hit enter and it's inserted in!
** Write this up in our tooling
   There are more details to this, but they are useful beyond apisnoop and for any of us working in spacemacs.  So I am starting up a FAQ answer in our tooling/iimacs/FAQ org.
* Conclusions || Next Steps
  It is relatively simple to set up a yasnippet, and it saves time when starting up a new org file!
  
  The next step is to catpure this in more detail in our tooling orgs.

* Footnotes

  If you've already started up your app, you can connect to it by executing the two blocks below, in order.
  If you haven't started it up yet, do so following the steps in [[file:~/ii/apisnoop/org/meta.org::*Welcome,%20ii%20dev!][meta.org]]  
  #+NAME: Connect org to postgres
  #+BEGIN_SRC emacs-lisp :results silent
    (sql-connect "apisnoop" (concat "*SQL: postgres:data*"))
    #+END_SRC
  #+NAME: Test Connection
  #+BEGIN_SRC sql-mode :results silent
    \conninfo
    #+END_SRC

