#+TITLE: Clean Repo Clean Heart
#+AUTHOR: Caleb
#+AUTHOR: Zach

* Purpose
  Organize repo to have focused domains and org files that relate only to that domain.  This is to help avoid accidents by over-tangling in org files, and to make the repo easier to understand
* Process  
** Isolate the areas that need fixing
  We could reorganize the folder structures to  have the various components at a top level, and each one contains its own app and deployment info 
  
  #+name: possible structure
  #+begin_example
    | Auditlogger
      - app
      - deployment
      -index.org
    | hasura
      - app
      - deployment
      - index.org
    org
    readme.org
  #+end_example
  
  it's a possible, and discussing it with the team we unanimously like it...so we're doing it.
** [1/4] Figure out what we don't need
*** DONE apps
    CLOSED: [2020-03-19 Thu 11:49]
**** D openapi
     this is a docker-compose setup, and anythiong docker-compose is from an older time that we no longer need to look back to. DELETED
**** D kubemacs
     this is a submodule, and not needed in our repo anymore. DELETED
**** D .env_sample and .loadenv
**** D docker-compose.yml
     anything docker compose DELETED
**** D pgpass_sample
     older but also incorrect port.  DELETED
**** D traefik.yaml
     older, we don't use traefik.  DELETED
*** TODO deployment
**** k8s
***** zz

***** D ZZ
      zz doesnt' use it. DELETED
***** ATTIC xip.io
      This is still interesting, so moved to attic
***** D kubemacs
      all this is contaioned in kubemacs own repo now. DELETED
***** ATTIC kubemacs.org
      Seems like there's quite a bit of research here, so we are preserving it in the attic.
***** ATTIC local
      don't think we are using it, but uncertainty means ATTIC
***** ATTIC hh
      don't think we are using it, but uncertainty means ATTIC
*** TODO kustomize
*** TODO org
** [0/5] Fix these areas
*** TODO Auditlogger
*** TODO Hasura
*** TODO webapp
*** TODO postgres
*** TODO pgadmin
** Test is works

** Move tickets org up to root, and separate into k8s and api tickets
