-- Create Table
-- #+NAME: api_swagger

CREATE TABLE api_swagger (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    -- version text NOT NULL,
    -- definition_id text NOT NULL,
    data jsonb NOT NULL
);

-- Index Table
-- #+NAME: general index the raw_swagger

CREATE INDEX idx_swagger_jsonb_ops ON api_swagger
  USING GIN (data jsonb_ops);
CREATE INDEX idx_swagger_jsonb_path_ops ON api_swagger
  USING GIN (data jsonb_path_ops);
