-- raw_audit_events

-- #+NAME: raw_audit_events

DROP TABLE raw_audit_events;
CREATE TABLE raw_audit_events (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
    bucket text,
    job text,
    data jsonb NOT NULL
);
