#!/bin/bash
set -x
set -e
# https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default
# https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce
# https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31582/
# http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31582/artifacts/bootstrap-e2e-master/
pwd
apt-get install wget curl -y
(mkdir master
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31582/artifacts/bootstrap-e2e-master/kube-apiserver-audit.log-20181104-1541372401.gz -O -| zcat > master/audit.log
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31582/artifacts/bootstrap-e2e-master/kube-apiserver-audit.log -O - >> master/audit.log
) &

# https://k8s-testgrid.appspot.com/sig-release-1.12-all
# https://k8s-testgrid.appspot.com/sig-release-1.12-all#gce-cos-1.12-default
# https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default
# https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/6808/

(mkdir 1.12
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/6808/artifacts/test-1789b1211d-master/kube-apiserver-audit.log -O 1.12/audit.log) &

# https://k8s-testgrid.appspot.com/sig-release-1.11-all#gce-cos-1.11-default
# https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-default
#https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-default/4267/

(mkdir 1.11
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-default/4267/artifacts/test-359c739436-master/kube-apiserver-audit.log -O 1.11/audit.log) &

# https://k8s-testgrid.appspot.com/sig-release-1.10-all#gce-cos-1.10-default
# https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-default
# https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-default/1446/

(mkdir 1.10
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-default/1446/artifacts/test-5881f7ab7e-master/kube-apiserver-audit.log -O 1.10/audit.log) &

# https://k8s-testgrid.appspot.com/sig-release-1.9-all#gce-cos-1.9-default
# https://gubernator.k8s.io/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable3-default

(mkdir 1.9
wget https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable3-default/368/artifacts/test-183d8deac8-master/kube-apiserver-audit.log -O 1.9/audit.log) &

# Download them all at the same time, wait for them all to finish
wait $(jobs -p)
