#!/bin/bash
set -x
set -e
mkdir -p data/processed-logs
for BRANCH in master 1.12 1.11 1.10 1.9;  do
  AUDIT=data/audit-logs/${BRANCH}/audit.log
  JSON=data/processed-logs/${BRANCH}.json
  LOG=data/processed-logs/${BRANCH}.log
  if [ ! $BRANCH == "master" ]; then
    # BRANCH let's us know which git tag to pull our openapi spec from
    BRANCH=release-$BRANCH
  fi
  python audit/logreview.py process-audit $AUDIT $BRANCH $JSON 2>&1 | tee $LOG &
done

wait $(jobs -p)
exit 0
