#+TITLE: APISnoop Readme

A suite of tools to assist kubernetes test-writing and investigate test coverage.

* Introduction

APISnoop is a collection of programs intended to run in a kubernetes cluster, that help with multiple aspects of conformance testing.
These programs include:
- snoopdb :: a postgres database for running queries about the state of conformance coverage.  This db starts up with audit events from a recent test run and the latest kubernetes api spec.  This allows you to run queries to see exactly which endpoints in the spec are covered by exactly which tests.  It can also be connected to auditlogger to create a more data-driven live-testing-environment.
- auditlogger :: a simple server that, when attached to a kubernetes cluster configured with an auditsink, will listen to all events in that cluster and insert them into the snoopdb's testing tables. This allows you to perform mock tests against a cluster and then query the results immediately to ensure that your mock test is hitting the endpoints you intended.

We use these components as part of [[https://github.com/humacs][humacs]] to create an emacs-based test-writing environment.  We also use snoopdb to generate the data for the site [[https://apisnoop.cncf.io]]

* Learning more
To learn more about the database, you can check out the readme [[./apps/snoopdb/README.md]]
 For auditlogger, you can check out the readme at [[./apps/auditlogger/README.org]]
