k8s_yaml(['deployment/k8s/graphql.yaml'])
docker_build('raiinbow/hasura', 'apps/hasura')
docker_build('raiinbow/postgres', 'apps/postgres')
# docker_build('raiinbow/auditlogger', 'apps/auditlogger')
k8s_resource('hasura', port_forwards='8080')
k8s_resource('postgres', port_forwards='54321')
