#+TITLE: TODO's

A place to capture todo's quickly as they come up

* Inbox
** DONE Remove printing the url's in the audit event
   CLOSED: [2020-07-13 Mon 05:39]
   It creates a lot of noise in the build and I am not sure if it is useful

** TODO Improve success statement for load_audit_events
   Right now it just says 'it worked' would be better to say 'audit events for 1.XX from bucket/job loaded'
** TODO Add build log announcements for each migration
   Could it be something like 'CREATE EXTENSIONS'  "EXTENSIONS CREATED" and "Create open api table" and "open api table defined and commented"
   it'd help to see where we are at in the build.  I think we could do it with cheeky select statements
** TODO fikgure out what to do with loading all past audit events in our weird code freeze time
   currently the latest release in our test runs is 1.20.0
   however, we are in the week of code freeze in the transition from 1.19 to 1.20 and during this time, 1.19.0 hasn't been officially released and there is no tag for it in github.
   this means we are going to be missing this release when loading up past tags.
   I am not sure the best way to handle this, or what to do in 3 months for 1.21...I don't wanna have to be updating the past releases script every time...let's find an elegant way of grabbing all past releases.
