#+TITLE: TODO's

A place to capture todo's quickly as they come up

* Inbox
** TODO Look into a helm chart repo potentially in apisnoop org
** DONE Remove printing the url's in the audit event
   CLOSED: [2020-07-13 Mon 05:39]
   It creates a lot of noise in the build and I am not sure if it is useful

** TODO Improve success statement for load_audit_events
   Right now it just says 'it worked' would be better to say 'audit events for 1.XX from bucket/job loaded'
** TODO Add build log announcements for each migration
   Could it be something like 'CREATE EXTENSIONS'  "EXTENSIONS CREATED" and "Create open api table" and "open api table defined and commented"
   it'd help to see where we are at in the build.  I think we could do it with cheeky select statements
** TODO fikgure out what to do with loading all past audit events in our weird code freeze time
   currently the latest release in our test runs is 1.20.0
   however, we are in the week of code freeze in the transition from 1.19 to 1.20 and during this time, 1.19.0 hasn't been officially released and there is no tag for it in github.
   this means we are going to be missing this release when loading up past tags.
   I am not sure the best way to handle this, or what to do in 3 months for 1.21...I don't wanna have to be updating the past releases script every time...let's find an elegant way of grabbing all past releases.

* iterations
- [x] snoopdb deployable via helm
- [x] basic docs started
- [ ] auditlogger is lifted and made its own repo
- [ ] auditlogger is added to cluster and accessible and talking to snoopdb (failure expected)
- [ ] snoopdb extended with testing schema (zach can solo here)
- [ ] apisnoop/auditlogger adjusted to insert into testing schema (zach solo)
- [ ] apisnoop/auditlogger listening and inserting events into apisnoop/db (no failure expected)
- [ ] snoopdb is added to humacs cluster and accessible
- [ ] tickets folder lifted and made its own repo
- [ ] tickets folder added to humacs setup and reachable when cluster all set up
- [ ] running code from org file in tickets folder shows up in snoopdb events
