# -*- ii: y; -*-
#+TITLE: tilt.localho.st config

* Bring up tilt
#+begin_src tmate :dir "."
  tilt up --host 0.0.0.0
#+end_src
* These files/folders map to these *.localho.st sites on 127.0.0.1
** http://tilt.localho.st
Our [[file:Tiltfile::k8s_yaml(kustomize('.'))][./Tiltfile]] uses the [[file:kustomization.yaml::kind:%20Kustomization][./kustomization.yaml]] to figure out what resources to
deploy. Changes to any file referenced will result in immediate changes to the
deployed resources. If [[file:Tiltfile::docker_build(][docker_build()]] entries are uncommented, those images will
be rebuilt, pushed, and pods restarted automatically.
** [[file:~/apisnoop/deployment/k8s/hasura][deployment/k8s/hasura]] -> [[../../../apps/hasura][apps/hasura]] -> http://hasura.localho.st
[[file:~/apisnoop/org/tables_and_views_bot.org][org/tables_and_views_bot.org]] can be tangled and primarily updates hasura, but can also be run interactively
** [[file:~/apisnoop/deployment/k8s/webapp][deployment/k8s/webapp]] -> [[../../../apps/webapp][apps/webapp]] -> [[http://apisnoop.localho.st/coverage]]
[[file:~/apisnoop/org/webapp.org][org/webapp.org]] can be tangled and primarily updates 
** [[../pgadmin][deployment/k8s/pgadmin]] -> http://pgadmin.localho.st
*** test sql connections
  #+NAME: Test Connection
  #+BEGIN_SRC sql-mode :results silent
    \conninfo
  #+END_SRC
*** permissions need to be super strict
So we use a set of [[file:~/apisnoop/deployment/k8s/pgadmin/deployment.yaml::-%20name:%20cp-servers-json][initContainers]] to copy [[file:~/apisnoop/deployment/k8s/pgadmin/configuration.yaml::servers.json][servers.json]] and [[file:~/apisnoop/deployment/k8s/pgadmin/configuration.yaml::pgpass:][pgpass]] out of a mounted configMap volume and set user/group/perms.
** [[file:~/apisnoop/deployment/k8s/postgres][deployment/k8s/postgres]] -> [[../../../apps/postgres][apps/postgres]]

* Visit these sites
- http://tilt.localho.st
- http://pgadmin.localho.st
- http://hasura.localho.st
- http://apisnoop.localho.st
