#!/bin/bash

export SCRIPT_PATH="$(dirname $(realpath $0))"

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    echo "install APISnoop into this cluster"
    kubectl get ns apisnoop || kubectl create ns apisnoop
    helm upgrade --install snoopdb -n apisnoop "$SCRIPT_PATH"/../charts/snoopdb
    helm upgrade --install auditlogger -n apisnoop "$SCRIPT_PATH"/../charts/auditlogger
fi
go get github.com/vmware-tanzu/sonobuoy@latest
