#!/bin/bash

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    echo "install APISnoop into this cluster"
    kubectl create ns apisnoop
    helm install snoopdb -n apisnoop charts/snoopdb
    helm install auditlogger -n apisnoop charts/auditlogger
fi
