#!/bin/bash

export SCRIPT_PATH="$(dirname $(realpath $0))"

EXTRA_ENV=""

if [[ -z "${TESTING_ONLY}" ]]; then
  EXTRA_ENV=""
else
  echo "TESTING!!!"
  EXTRA_ENV="--set extraEnv[0].name=TESTING_ONLY --set extraEnv[0].value=on"

if [ -f /var/run/secrets/kubernetes.io/serviceaccount/namespace ]; then
    echo "install APISnoop into this cluster"
    kubectl get ns apisnoop || kubectl create ns apisnoop
    helm upgrade --install $EXTRA_ENV snoopdb -n apisnoop "$SCRIPT_PATH"/../charts/snoopdb
    helm upgrade --install auditlogger -n apisnoop "$SCRIPT_PATH"/../charts/auditlogger
fi
go get github.com/vmware-tanzu/sonobuoy@latest
