# kind Cluster apiVersion

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# WARNING: It is _strongly_ recommended that you keep this the default
# (127.0.0.1) for security reasons. However it is possible to change this.
# networking:
#   apiServerAddress: "${KIND_APISERVER_ADDRESS}"
#   apiServerPort: 61443

# We need audit-{policy,sink}.yaml provided to the apiserver
# targeting apisnoop pods with host networking: snoopdb + auditlogger
# so the apiserver can log/auditsink to itself
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "audit-webhook-config-file": "/etc/kubernetes/pki/audit/sink.yaml"
        "audit-policy-file": "/etc/kubernetes/pki/audit/policy.yaml"

nodes:
  # Second entry under nodes
  - role: control-plane
    extraMounts:
      - hostPath: audit
        containerPath: /etc/kubernetes/pki/audit
        readOnly: True
      - hostPath: manifests/apisnoop.yaml
        containerPath: /etc/kubernetes/manifests/apisnoop.yaml
        readOnly: True
    # we want to reach psql from our host
    extraPortMappings:
      - containerPort: 5432
        hostPort: 5432
    # - containerPort: 80
    #   hostPort: 80
    # - containerPort: 443
    #   hostPort: 443
    # - containerPort: 6443
    #   hostPort: 6443
    # - containerPort: 10350
    #   hostPort: 10350

  - role: worker
    extraMounts:
      # - containerPath: /var/local-path-provisioner
      #   hostPath: /tmp/workspace/pvcs
      #   readOnly: False
      - containerPath: /var/run/docker.sock
        hostPath: /var/run/docker.sock
        readOnly: False
      - containerPath: /var/host/tmp
        hostPath: /tmp
        readOnly: False
