# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # our configs
  config.vm.synced_folder ".", "/config"
  # our kubeadm supporting audit-webhooks
  config.vm.synced_folder "../../../kubernetes/_output/local/bin/linux/amd64", "/binaries"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4092"
  end
  config.vm.provision "docker"
  config.vm.provision "shell", inline: <<-SHELL
    usermod -aG docker vagrant
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
    deb http://apt.kubernetes.io/ kubernetes-xenial main
    EOF
    apt-get update
    apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  SHELL
end
