#+TITLE: Lost Endpoints in testing
#+PROPERTY: header-args:sql-mode :product postgres :noweb yes :comments off

* purpose
We have a PR: https://github.com/kubernetes/kubernetes/pull/89753, that uses our sql query to show that if the functionw as promoted, it would cover 5 previously uncovered endpoints.

This PR was merged, but some of these endpoints still show as untested.  why?

* The endpoints

createCoreV1NamespacedEvent
deleteCoreV1NamespacedEvent
listCoreV1EventForAllNamespaces
patchCoreV1NamespacedEvent
readCoreV1NamespacedEvent
* The test
  should ensure that an event can be fetched, patched, deleted, and listed"

* confirm test is in our audit event
 It is a conformance test, and so should show up here.
  #+begin_src sql-mode
    select testname, file
      from test
     where codename like '%should ensure that an event can be fetched, patched, deleted, and listed%';
  #+end_src

  #+RESULTS:
  #+begin_SRC example
           testname         |              file
  --------------------------+---------------------------------
   Event resource lifecycle | test/e2e/apimachinery/events.go
  (1 row)

  #+end_SRC
and it does!

what endpoints does it hit?


#+begin_src sql-mode
  select endpoint
    from audit_event
   where test like '%should ensure that an event can be fetched, patched, deleted, and listed%'
   group by endpoint;
#+end_src

#+RESULTS:
#+begin_SRC example
                    endpoint
------------------------------------------------
 createAuthorizationV1SubjectAccessReview
 createCoreV1Namespace
 createRbacAuthorizationV1NamespacedRoleBinding
 deleteCoreV1Namespace
 listCoreV1NamespacedServiceAccount
 listCoreV1Node
(6 rows)

#+end_SRC
* The issue
  Our mock test function shows namespaceEvents being hit, but the actual test is only hitting the 'Namespace' endpoints and not the event endpoints.
* do these endpoints still exist?
  #+begin_src sql-mode
    select endpoint
      from open_api
     where endpoint like '%CoreV1NamespacedEvent'
       and release = '1.19.0';
  #+end_src

  #+RESULTS:
  #+begin_SRC example
             endpoint
  ------------------------------
   createCoreV1NamespacedEvent
   deleteCoreV1NamespacedEvent
   listCoreV1NamespacedEvent
   patchCoreV1NamespacedEvent
   readCoreV1NamespacedEvent
   replaceCoreV1NamespacedEvent
   watchCoreV1NamespacedEvent
  (7 rows)

  #+end_SRC
