# audit-sink.yaml
# Currently hardcoded. Would be good if we had dynamic.

apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://127.0.0.1:9900/events
  name: auditsink-cluster
contexts:
- context:
    cluster: auditsink-cluster
    user: ""
  name: auditsink-context
current-context: auditsink-context
users: []
preferences: {}
