CREATE UNLOGGED TABLE audit_event (
  release text,
  release_date text,
  audit_id text NOT NULL,
  endpoint text,
  useragent text,
  test text,
  test_hit boolean,
  conf_test_hit boolean,
  data jsonb NOT NULL,
  source text,
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingested_at timestamp DEFAULT CURRENT_TIMESTAMP);

comment on table audit_event is 'each audit event taken from the logs of an e2e test suite run';

comment on column audit_event.release is 'release this test suite was run for';
comment on column audit_event.release_date is 'canonical release, or date of run if version has not been released yet';
comment on column audit_event.audit_id is 'audit event id as given in log.  Note these are not necessarily unique.';
comment on column audit_event.endpoint is 'the endpoint hit by this audit event';
comment on column audit_event.useragent is 'the useragent of the event, stored in events request header';
comment on column audit_event.test is 'the test codename if it can be extracted from useragent, else null';
comment on column audit_event.test_hit is 'is this event one where a test is hitting an endpoint, as seen in its useragent?';
comment on column audit_event.conf_test_hit is 'is this event one where a conformance test is hitting an endpoint?';
comment on column audit_event.data is 'the full json of the audit event';
comment on column audit_event.source is 'the url location of the bucket where the test run logs are stored';
comment on column audit_event.id is 'generated id, this will be unique';
comment on column audit_event.ingested_at is 'the time at which the audit_event was added to this table';
