#+TITLE: Debug the WebUI
#+AUTHOR: Zach Mandeville
#+DATE: 2020-24-03

* Purpose
  Working on the document-flow branch to ready it for a merge.
  Currently the webui is giving me an error 500 on the main page.  I want to see coverage on this page and the ability to go into any sunburst and see it too
* Process
** Look at the console logs for data being provided
   The error on the front page is ~500: cannot read timestamp of undefined~.  Looking at the code, we are trying to grab the first bit of coverage and then grab its timestamp.  Coverage is a store that is derived from our buckets and jobs and our stable endopint stats (it refers to coverage stats of the default bucket and job).

   When console logging coverage Ic an see it's an empty array, so ~coverage[0]~ would be undefined and ~coverage[0].timestamp~ will thow an error.

   When you go onto the main page, we query our graphql endpoint for all the buckets and our current stable endpoint stats.  When I console log both, I can see that neither return data.  This makes me think there is a missing connection to our endpoint
** Sanitty Check that Hsuara is up and functional 
   I want to ensure our endpoint is up and has data that can be queried.  IF not, it doesn't matter what code changes we do in the web ui, it will never have the data I need.

When I try to get to the console of hasura (hasura.zz.ii.coop) it asks me to log in and then after loading for quite sometime I get 'failed to fetch from db'.  So something is off.   We have basic auth set up, but 0perhaps hasura is designed to ping other parts of its app, and the basic auth is screwing it up?
*** Turn off basic auth
    We can turn this off by removing all referencdes to patch-ingress-auth.yaml in our kustomization.yaml patches
    Doing this enabled me to access the console quickly and see all the data was there. 
*** Check data again
    My git checkout was out of sync with the origin and missing some necessary patch files.  Investigating auth highlighted this and let me fix it.  When I confirmed I was in sync with origin/document-flow then the front page loaded.  However the sunburst still won't load
** Console log the sunburst pages
   Sunburst is expecting a payload derived from endpoint coverage.  Whe I looked at that query, I saw a refrence to a "details" key...which is a relationship built with our hasura migrations, by building an object relatinship b/w endpoint_coverage and api_operation.  This used to be brought up with our metadata migration, but this was removed during ou8r great cleaning as it contained references to now non-existen tables.
** Build details object relationship again
When I built it in the hasura console and loaded again it worked!
So now we need to export and make sure the latest metadata is part of our migrations.
** The new metadata
   #+begin_src json 
     {"functions":[],"remote_schemas":[],"query_collections":[],"allowlist":[],"version":2,"tables":[{"table":"api_operation","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"audit_event","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"bucket_job_swagger","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"endpoint_coverage","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[{"using":{"manual_configuration":{"remote_table":"api_operation","column_mapping":{"bucket":"bucket","operation_id":"operation_id","job":"job"}}},"name":"details","comment":null}],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"endpoints_hit_by_new_test","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"projected_change_in_coverage","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"stable_endpoint_stats","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"tests","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"untested_stable_core_endpoints","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]},{"table":"useragents","is_enum":false,"configuration":{"custom_root_fields":{"select":null,"select_by_pk":null,"select_aggregate":null,"insert":null,"update":null,"delete":null},"custom_column_names":{}},"object_relationships":[],"array_relationships":[],"insert_permissions":[],"select_permissions":[],"update_permissions":[],"delete_permissions":[],"event_triggers":[],"computed_fields":[]}]}

   #+end_src
* Conclusion | Next Steps

# Local Variables:
# ii: enabled
# End:
