#+TITLE: Ticket 59
#+AUTHOR: Hippie Hacker
#+AUTHOR: Zach Mandeville
#+PROPERTY: header-args :exports both :eval never-export

* The Ticket
  [[https://gitlab.ii.coop/apisnoop/apisnoop_v3/issues/59][Gitlab Link]]
  
  #+BEGIN_QUOTE
In our podspec_field_report there are array and subtype fields that should be hit (like volume and containers), but show 0 hits entirely.  This doesn't feel accurate, and we should look into why these fields might not be hit...or what needs to change in our views to properly account for hits on array/subtype type fields.
  #+END_QUOTE
* Process
  We created a new set of podspec reports in our[[file:tix_61.org][ exploration of ticket 61]], we will use them to explore why our arrays and subtypes may be showing 0 coverage.
  The hits are calculated in our initial podspec coverage report, and so we will dissect each section of that query to ensure that our fields are being counted correctly.
** Dissect the Revised PodSpec Materialized View
 Ensuring we have the hits we are looking for:
*** Each sub query
**** where kind = 'Pod' fieldpath = 'spec'

  #+BEGIN_SRC sql-mode
    SELECT DISTINCT
      jsonb_object_keys(request_object -> 'spec'::text) AS podspec_field,
      count(event_field.event_field) AS hits
      FROM events_by_gvkrv,
           LATERAL
             jsonb_object_keys(events_by_gvkrv.request_object -> 'spec'::text) event_field(event_field)
     WHERE kind = 'Pod'
       AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}')) -- api_version doesn't contain alpha or beta;
     GROUP BY podspec_field
     ORDER BY podspec_field;
  #+END_SRC

  #+RESULTS:
  #+begin_src sql-mode
           podspec_field         | hits  
  -------------------------------+-------
   activeDeadlineSeconds         |    40
   affinity                      |  1256
   automountServiceAccountToken  |    96
   containers                    | 20344
   dnsConfig                     |    16
   dnsPolicy                     | 20344
   enableServiceLinks            | 20344
   hostAliases                   |     8
   hostIPC                       |    16
   hostname                      |  5614
   hostNetwork                   |  2665
   hostPID                       |    16
   imagePullSecrets              |     8
   initContainers                |  1347
   nodeName                      |  9086
   nodeSelector                  |  1604
   priority                      |  1088
   priorityClassName             |  1342
   readinessGates                |     8
   restartPolicy                 | 20344
   runtimeClassName              |    36
   schedulerName                 | 20344
   securityContext               | 20344
   serviceAccount                |  7589
   serviceAccountName            |  7589
   subdomain                     |  5398
   terminationGracePeriodSeconds | 20344
   tolerations                   |  2883
   volumes                       | 14623
  (29 rows)

  #+end_src

**** where kind = 'PodTemplate' fieldpath = 'template.spec'
  
  PodTemplate is hit, but not much.

  #+BEGIN_SRC sql-mode
      SELECT DISTINCT
        jsonb_object_keys(request_object -> 'template' -> 'spec'::text) AS podspec_field,
        count(event_field.event_field) AS hits
        FROM events_by_gvkrv,
             LATERAL
               jsonb_object_keys(events_by_gvkrv.request_object -> 'template'-> 'spec'::text) event_field(event_field)
       WHERE kind = 'PodTemplate'
         AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}'))
       GROUP BY podspec_field
       ORDER BY podspec_field;
  #+END_SRC

  #+RESULTS:
  #+begin_src sql-mode
           podspec_field         | hits 
  -------------------------------+------
   containers                    | 4920
   dnsPolicy                     | 4920
   restartPolicy                 | 4920
   schedulerName                 | 4920
   securityContext               | 4920
   terminationGracePeriodSeconds | 4920
  (6 rows)

  #+end_src

**** where kind = 'DaemonSet, Deployment, ReplicationController, StatefulSet, Job,ReplicaSet' fieldpath = 'spec.template.spec'
  
  #+BEGIN_SRC sql-mode
    SELECT DISTINCT
      -- test,
      jsonb_object_keys(request_object -> 'spec' -> 'template' -> 'spec'::text) AS podspec_field,
      count(event_field.event_field) AS hits
      FROM events_by_gvkrv,
           LATERAL
             jsonb_object_keys(events_by_gvkrv.request_object -> 'spec' -> 'template'-> 'spec'::text) event_field(event_field)
     WHERE kind = ANY('{DaemonSet, Deployment, ReplicationController, StatefulSet, Job,ReplicaSet}')
       AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}'))
     GROUP BY podspec_field; 
  #+END_SRC

  #+RESULTS:
  #+begin_src sql-mode
           podspec_field         | hits  
  -------------------------------+-------
   containers                    | 17710
   dnsPolicy                     | 17710
   hostNetwork                   |  1637
   nodeName                      |  3590
   nodeSelector                  |  2041
   priorityClassName             |  2421
   restartPolicy                 | 17710
   schedulerName                 | 17710
   securityContext               | 17710
   serviceAccount                |  5836
   serviceAccountName            |  5836
   terminationGracePeriodSeconds | 17710
   tolerations                   |  2125
   volumes                       |  8754
  (14 rows)

  #+end_src

*** The entire query

   #+NAME: Count before going all the way down
   #+BEGIN_SRC sql-mode
     select distinct podspec_field AS field
                     , sum(hits) AS hits
     FROM (

     SELECT DISTINCT
       jsonb_object_keys(request_object -> 'spec'::text) AS podspec_field,
       count(event_field.event_field) AS hits
       FROM events_by_gvkrv,
            LATERAL
              jsonb_object_keys(events_by_gvkrv.request_object -> 'spec'::text) event_field(event_field)
      WHERE kind = 'Pod'
        AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}')) -- api_version doesn't contain alpha or beta;
      GROUP BY podspec_field
           UNION
     SELECT DISTINCT
       jsonb_object_keys(request_object -> 'template' -> 'spec'::text) AS podspec_field,
       count(event_field.event_field) AS hits
       FROM events_by_gvkrv,
            LATERAL
              jsonb_object_keys(events_by_gvkrv.request_object -> 'template'-> 'spec'::text) event_field(event_field)
      WHERE kind = 'PodTemplate'
        AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}'))
      GROUP BY podspec_field
           UNION
     SELECT DISTINCT
       jsonb_object_keys(request_object -> 'spec' -> 'template' -> 'spec'::text) AS podspec_field,
       count(event_field.event_field) AS hits
       FROM events_by_gvkrv,
            LATERAL
              jsonb_object_keys(events_by_gvkrv.request_object -> 'spec' -> 'template'-> 'spec'::text) event_field(event_field)
      WHERE kind = ANY('{DaemonSet, Deployment, ReplicationController, StatefulSet, Job,ReplicaSet}')
        AND NOT (lower(api_version) ~~ ANY('{%alpha%, %beta%}'))
      GROUP BY podspec_field
      ) as x
      group by podspec_field
                                                           ;
  #+END_SRC

  #+RESULTS: Count before going all the way down
  #+begin_src sql-mode
               field             | hits  
  -------------------------------+-------
   activeDeadlineSeconds         |    40
   affinity                      |  1256
   automountServiceAccountToken  |    96
   containers                    | 42974
   dnsConfig                     |    16
   dnsPolicy                     | 42974
   enableServiceLinks            | 20344
   hostAliases                   |     8
   hostIPC                       |    16
   hostname                      |  5614
   hostNetwork                   |  4302
   hostPID                       |    16
   imagePullSecrets              |     8
   initContainers                |  1347
   nodeName                      | 12676
   nodeSelector                  |  3645
   priority                      |  1088
   priorityClassName             |  3763
   readinessGates                |     8
   restartPolicy                 | 42974
   runtimeClassName              |    36
   schedulerName                 | 42974
   securityContext               | 42974
   serviceAccount                | 13425
   serviceAccountName            | 13425
   subdomain                     |  5398
   terminationGracePeriodSeconds | 42974
   tolerations                   |  5008
   volumes                       | 23377
  (29 rows)

  #+end_src
 
  And comparing the two we get the same number of records.

   #+NAME: Comparison of orig and revised podspec
   #+BEGIN_SRC sql-mode
     SELECT
       (
         SELECT
           count(*)
           FROM
               podspec_field_coverage_material
       ) AS original_count,
       (
         SELECT
           count(*)
           FROM
               revised_podspec_field_coverage_material
         ) as revised_count;

   #+END_SRC

   #+RESULTS: Comparison of orig and revised podspec
   #+begin_src sql-mode
    original_count | revised_count 
   ----------------+---------------
              6572 |          6572
   (1 row)

   #+end_src
  
   Success!

*** Summary
 #+BEGIN_SRC sql-mode
     select distinct podspec_field AS field
                     , sum(hits) AS hits
     from revised_podspec_field_coverage
     group by podspec_field
     ;
 #+END_SRC

 #+RESULTS:
 #+begin_src sql-mode
              field             | hits  
 -------------------------------+-------
  activeDeadlineSeconds         |    40
  affinity                      |  1256
  automountServiceAccountToken  |    96
  containers                    | 42974
  dnsConfig                     |    16
  dnsPolicy                     | 42974
  enableServiceLinks            | 20344
  hostAliases                   |     8
  hostIPC                       |    16
  hostname                      |  5614
  hostNetwork                   |  4302
  hostPID                       |    16
  imagePullSecrets              |     8
  initContainers                |  1347
  nodeName                      | 12676
  nodeSelector                  |  3645
  priority                      |  1088
  priorityClassName             |  3763
  readinessGates                |     8
  restartPolicy                 | 42974
  runtimeClassName              |    36
  schedulerName                 | 42974
  securityContext               | 42974
  serviceAccount                | 13425
  serviceAccountName            | 13425
  subdomain                     |  5398
  terminationGracePeriodSeconds | 42974
  tolerations                   |  5008
  volumes                       | 23377
 (29 rows)

 #+end_src

*** Conclusion
    We are accurately counting hits for array fields like containers and volumes here, so the issue must not be within this report but somewhere further down the line. 

** Check Count For 601: PodSpec Field Coverage View
   Are hits accurately accounted for in this view?
 #+NAME: 601 field counts
 #+BEGIN_SRC sql-mode
   select distinct podspec_field AS field
                   , sum(hits) AS hits
   FROM revised_podspec_field_coverage_material
   GROUP BY podspec_field;
 #+END_SRC

 #+RESULTS: 601 field counts
 #+begin_src sql-mode
              field             | hits  
 -------------------------------+-------
  activeDeadlineSeconds         |    40
  affinity                      |  1256
  automountServiceAccountToken  |    96
  containers                    | 42974
  dnsConfig                     |    16
  dnsPolicy                     | 42974
  enableServiceLinks            | 20344
  hostAliases                   |     8
  hostIPC                       |    16
  hostname                      |  5614
  hostNetwork                   |  4302
  hostPID                       |    16
  imagePullSecrets              |     8
  initContainers                |  1347
  nodeName                      | 12676
  nodeSelector                  |  3645
  priority                      |  1088
  priorityClassName             |  3763
  readinessGates                |     8
  restartPolicy                 | 42974
  runtimeClassName              |    36
  schedulerName                 | 42974
  securityContext               | 42974
  serviceAccount                | 13425
  serviceAccountName            | 13425
  subdomain                     |  5398
  terminationGracePeriodSeconds | 42974
  tolerations                   |  5008
  volumes                       | 23377
 (29 rows)

 #+end_src
 
They are! So we move on.
** Check Count For 602: PodSpec Field Summary View
  
   Are hits accurately accounted for in this view?
 #+NAME: 602 field counts
 #+BEGIN_SRC sql-mode
   select distinct podspec_field AS field
                   , sum(other_hits + e2e_hits + conf_hits) AS hits
   FROM revised_podspec_field_summary
   GROUP BY podspec_field;
 #+END_SRC

 #+RESULTS: 602 field counts
 #+begin_src sql-mode
              field             | hits  
 -------------------------------+-------
  activeDeadlineSeconds         |    40
  affinity                      |  1256
  automountServiceAccountToken  |    96
  containers                    | 42974
  dnsConfig                     |    16
  dnsPolicy                     | 42974
  enableServiceLinks            | 20344
  ephemeralContainers           |     0
  hostAliases                   |     8
  hostIPC                       |    16
  hostname                      |  5614
  hostNetwork                   |  4302
  hostPID                       |    16
  imagePullSecrets              |     8
  initContainers                |  1347
  nodeName                      | 12676
  nodeSelector                  |  3645
  overhead                      |     0
  preemptionPolicy              |     0
  priority                      |  1088
  priorityClassName             |  3763
  readinessGates                |     8
  restartPolicy                 | 42974
  runtimeClassName              |    36
  schedulerName                 | 42974
  securityContext               | 42974
  serviceAccount                | 13425
  serviceAccountName            | 13425
  shareProcessNamespace         |     0
  subdomain                     |  5398
  terminationGracePeriodSeconds | 42974
  tolerations                   |  5008
  topologySpreadConstraints     |     0
  volumes                       | 23377
 (34 rows)

 #+end_src

  They are! So we move on.
** Check Count For 603: PodSpec Field mid Report View
   Are hits accurately accounted for in this view?
  #+NAME: 603 field counts
  #+BEGIN_SRC sql-mode
    select distinct podspec_field AS field
                    , sum(other_hits + e2e_hits + conf_hits) AS hits
    FROM revised_podspec_field_mid_report
    GROUP BY podspec_field;
  #+END_SRC

  #+RESULTS: 603 field counts
  #+begin_src sql-mode
               field             |  hits   
  -------------------------------+---------
   activeDeadlineSeconds         |    2360
   affinity                      |       0
   automountServiceAccountToken  |    5664
   containers                    |       0
   dnsConfig                     |       0
   dnsPolicy                     | 2535466
   enableServiceLinks            | 1200296
   ephemeralContainers           |       0
   hostAliases                   |       0
   hostIPC                       |     944
   hostname                      |  331226
   hostNetwork                   |  253818
   hostPID                       |     944
   imagePullSecrets              |       0
   initContainers                |       0
   nodeName                      |  747884
   nodeSelector                  |  215055
   overhead                      |       0
   preemptionPolicy              |       0
   priority                      |   64192
   priorityClassName             |  222017
   readinessGates                |       0
   restartPolicy                 | 2535466
   runtimeClassName              |    2124
   schedulerName                 | 2535466
   securityContext               |       0
   serviceAccount                |  792075
   serviceAccountName            |  792075
   shareProcessNamespace         |       0
   subdomain                     |  318482
   terminationGracePeriodSeconds | 2535466
   tolerations                   |       0
   topologySpreadConstraints     |       0
   volumes                       |       0
  (34 rows)

  #+end_src
  
  They are not!  What's changed?
  This report brings in a new view, the kind_field_path field, and is checking for where the field_path matches the kfp.field_path based on a regex substitution.
  However, this was an intermediate view. We hadn't fully walked through all the kind_field_paths until we did our recusive query.  We should pull from this view instead.
  The recursive view has far more paths, and we want to ensure we are looking at just the top most and not all auxiliary and dependent fields.  These will show as the ${fieldname}.${furtherpath}.  So we can update our where clause to exclude any field_paths with a dot in their name. Then we can do a simple 'field_path = field_path' matching.  
  
** Correct 603 to use kind_field_path_recursive 
   
 #+NAME: podspec_field_mid_recusie
 #+BEGIN_SRC sql-mode :results silent
   create or replace view corrected_podspec_field_mid_report as
   -- select distinct
   --   field_name as podspec_field,
   --   0 as other_hits,
   --   0 as e2e_hits,
   --   0 as conf_hits,
   --   release,
   --   deprecated,
   --   feature_gated as gated,
   --   required,
   --   field_kind,
   --   field_type
   --   from api_schema_field
   --  where field_schema like '%PodSpec%'
   --  UNION
   select distinct podspec_field,
         sum(other_hits) as other_hits,
         sum(e2e_hits) as e2e_hits,
         sum(conf_hits) as conf_hits,
         kfp.release,
         kfp.deprecated,
         kfp.gated,
         kfp.required,
         kfp.field_kind,
         kfp.field_type
   from revised_podspec_field_summary pfs, kind_field_path_recursion kfp
   where 
     kfp.kind = 'io.k8s.api.core.v1.PodSpec'
     and pfs.podspec_field = kfp.field_path
   group by podspec_field, kfp.release, kfp.deprecated, kfp.gated, kfp.required, kfp.field_kind, kfp.field_type
   order by conf_hits, e2e_hits, other_hits;
 #+END_SRC
 
 #+NAME: Count corrected_podspec_field_mid_report
 #+BEGIN_SRC sql-mode
   SELECT
     podspec_field,
     sum(other_hits + e2e_hits + conf_hits) as total_hits,
     e2e_hits,
     conf_hits,
     other_hits,
     field_type
     FROM
         corrected_podspec_field_mid_report
         GROUP BY podspec_field, e2e_hits, conf_hits, other_hits, field_type;

 #+END_SRC

 #+RESULTS: Count corrected_podspec_field_mid_report
 #+begin_src sql-mode
          podspec_field         | total_hits | e2e_hits | conf_hits | other_hits | field_type 
 -------------------------------+------------+----------+-----------+------------+------------
  activeDeadlineSeconds         |         40 |        8 |        14 |         18 | integer
  affinity                      |       1256 |       43 |         0 |       1213 | subtype
  automountServiceAccountToken  |         96 |       36 |        60 |          0 | boolean
  containers                    |      42974 |    13194 |      2063 |      27717 | array
  dnsConfig                     |         16 |       16 |         0 |          0 | subtype
  dnsPolicy                     |      42974 |    13194 |      2063 |      27717 | string
  enableServiceLinks            |      20344 |     6506 |      1741 |      12097 | boolean
  ephemeralContainers           |          0 |        0 |         0 |          0 | array
  hostAliases                   |          8 |        0 |         8 |          0 | array
  hostIPC                       |         16 |       16 |         0 |          0 | boolean
  hostname                      |       5614 |       85 |        60 |       5469 | string
  hostNetwork                   |       4302 |     1574 |        41 |       2687 | boolean
  hostPID                       |         16 |       16 |         0 |          0 | boolean
  imagePullSecrets              |          8 |        0 |         8 |          0 | array
  initContainers                |       1347 |     1315 |        32 |          0 | array
  nodeName                      |      12676 |     4170 |       127 |       8379 | string
  nodeSelector                  |       3645 |      257 |       128 |       3260 | object
  overhead                      |          0 |        0 |         0 |          0 | object
  preemptionPolicy              |          0 |        0 |         0 |          0 | string
  priority                      |       1088 |       83 |       105 |        900 | integer
  priorityClassName             |       3763 |       32 |         0 |       3731 | string
  readinessGates                |          8 |        8 |         0 |          0 | array
  restartPolicy                 |      42974 |    13194 |      2063 |      27717 | string
  runtimeClassName              |         36 |       36 |         0 |          0 | string
  schedulerName                 |      42974 |    13194 |      2063 |      27717 | string
  securityContext               |      42974 |    13194 |      2063 |      27717 | subtype
  serviceAccount                |      13425 |     1199 |       201 |      12025 | string
  serviceAccountName            |      13425 |     1199 |       201 |      12025 | string
  shareProcessNamespace         |          0 |        0 |         0 |          0 | boolean
  subdomain                     |       5398 |       85 |        60 |       5253 | string
  terminationGracePeriodSeconds |      42974 |    13194 |      2063 |      27717 | integer
  tolerations                   |       5008 |       83 |       105 |       4820 | array
  topologySpreadConstraints     |          0 |        0 |         0 |          0 | array
  volumes                       |      23377 |     6903 |       876 |      15598 | array
 (34 rows)

 #+end_src
 
 Fantastic!  There we are.

** Update 604: PodSpec Field Report View
   We can now have this podspec field report view draw from our corrected mid_report.
#+NAME: revised podspec_field_hits
#+BEGIN_SRC sql-mode :results silent
  create or replace view corrected_podspec_field_report as
  select distinct podspec_field,
        sum(other_hits) as other_hits,
        sum(e2e_hits) as e2e_hits,
        sum(conf_hits) as conf_hits,
        release,
        deprecated,
        gated,
        required,
        field_kind,
        field_type
  from corrected_podspec_field_mid_report
  group by podspec_field, release, deprecated, gated, required, field_kind, field_type
  order by conf_hits, e2e_hits, other_hits;
#+END_SRC

And check the new numbers.

#+BEGIN_SRC sql-mode
select * from corrected_podspec_field_report;
#+END_SRC

#+RESULTS:
#+begin_src sql-mode
         podspec_field         | other_hits | e2e_hits | conf_hits | release | deprecated | gated | required |                 field_kind                  | field_type 
-------------------------------+------------+----------+-----------+---------+------------+-------+----------+---------------------------------------------+------------
 ephemeralContainers           |          0 |        0 |         0 | alpha   | f          | t     | f        | io.k8s.api.core.v1.EphemeralContainer       | array
 overhead                      |          0 |        0 |         0 | alpha   | f          | t     | f        | integer                                     | object
 preemptionPolicy              |          0 |        0 |         0 | alpha   | f          | t     | f        | string                                      | string
 shareProcessNamespace         |          0 |        0 |         0 | beta    | f          | f     | f        | integer                                     | boolean
 topologySpreadConstraints     |          0 |        0 |         0 | alpha   | f          | t     | f        | io.k8s.api.core.v1.TopologySpreadConstraint | array
 readinessGates                |          0 |        8 |         0 | ga      | f          | f     | f        | io.k8s.api.core.v1.PodReadinessGate         | array
 dnsConfig                     |          0 |       16 |         0 | ga      | f          | f     | f        | io.k8s.api.core.v1.PodDNSConfig             | subtype
 hostIPC                       |          0 |       16 |         0 | ga      | f          | f     | f        | integer                                     | boolean
 hostPID                       |          0 |       16 |         0 | ga      | f          | f     | f        | integer                                     | boolean
 priorityClassName             |       3731 |       32 |         0 | ga      | f          | f     | f        | string                                      | string
 runtimeClassName              |          0 |       36 |         0 | beta    | f          | f     | f        | string                                      | string
 affinity                      |       1213 |       43 |         0 | ga      | f          | f     | f        | io.k8s.api.core.v1.Affinity                 | subtype
 hostAliases                   |          0 |        0 |         8 | ga      | f          | f     | f        | io.k8s.api.core.v1.HostAlias                | array
 imagePullSecrets              |          0 |        0 |         8 | ga      | f          | f     | f        | io.k8s.api.core.v1.LocalObjectReference     | array
 activeDeadlineSeconds         |         18 |        8 |        14 | ga      | f          | f     | f        | integer                                     | integer
 initContainers                |          0 |     1315 |        32 | ga      | f          | f     | f        | io.k8s.api.core.v1.Container                | array
 hostNetwork                   |       2687 |     1574 |        41 | ga      | f          | f     | f        | integer                                     | boolean
 automountServiceAccountToken  |          0 |       36 |        60 | ga      | f          | f     | f        | integer                                     | boolean
 subdomain                     |       5253 |       85 |        60 | ga      | f          | f     | f        | string                                      | string
 hostname                      |       5469 |       85 |        60 | ga      | f          | f     | f        | string                                      | string
 priority                      |        900 |       83 |       105 | ga      | f          | f     | f        | integer                                     | integer
 tolerations                   |       4820 |       83 |       105 | ga      | f          | f     | f        | io.k8s.api.core.v1.Toleration               | array
 nodeName                      |       8379 |     4170 |       127 | ga      | f          | f     | f        | string                                      | string
 nodeSelector                  |       3260 |      257 |       128 | ga      | f          | f     | f        | integer                                     | object
 serviceAccount                |      12025 |     1199 |       201 | ga      | t          | f     | f        | string                                      | string
 serviceAccountName            |      12025 |     1199 |       201 | ga      | f          | f     | f        | string                                      | string
 volumes                       |      15598 |     6903 |       876 | ga      | f          | f     | f        | io.k8s.api.core.v1.Volume                   | array
 enableServiceLinks            |      12097 |     6506 |      1741 | ga      | f          | f     | f        | integer                                     | boolean
 containers                    |      27717 |    13194 |      2063 | ga      | f          | f     | t        | io.k8s.api.core.v1.Container                | array
 dnsPolicy                     |      27717 |    13194 |      2063 | ga      | f          | f     | f        | string                                      | string
 restartPolicy                 |      27717 |    13194 |      2063 | ga      | f          | f     | f        | string                                      | string
 schedulerName                 |      27717 |    13194 |      2063 | ga      | f          | f     | f        | string                                      | string
 securityContext               |      27717 |    13194 |      2063 | ga      | f          | f     | f        | io.k8s.api.core.v1.PodSecurityContext       | subtype
 terminationGracePeriodSeconds |      27717 |    13194 |      2063 | ga      | f          | f     | f        | integer                                     | integer
(34 rows)

#+end_src

We have all the fields as before, but now the array and subtypes are showing hits if they do truly have hits.  This is showing that all ga podspec_fields are tested, though several have no conformance tests.

* Conclusion and Next Steps
  All the original work was good except for the kind_field_path view we drew from to get the deprecated,gated,required,etc columns.  Switching to kind_field_path recursion, with an updated where clause to match the structure of this view, brought in the correct numbers for arrays and subtypes.
  
  From the combined work in 59 and 61, we can now update our podspec coverage views in meta.org to accurately account for arrays and subtypes.
* Footnotes
** Connect to Database
    If you already have your db and hasura endpoint up and running:
 - [ ] Connect to your postgres db from within this file
   You'll want execute this code block by moving your cursor within and typing =,,=
  
   #+NAME: Connect org to postgres
   #+BEGIN_SRC emacs-lisp :results silent
     (sql-connect "apisnoop" (concat "*SQL: postgres:data*"))
   #+END_SRC

 - [ ] Test your connection works
   You can run this sql block, and it see a message in your minbuffer like:
   : You are connected to database "apisnoop" as user "apisnoop" on host "localhost" at port "10041".

   #+NAME: Test Connection
   #+BEGIN_SRC sql-mode :results silent
   \conninfo
   #+END_SRC

 If the db is not running, or hasn't been setup yet, follow the instructions in [[file:~/ii/apisnoop_v3/org/meta.org::*Welcome,%20ii%20dev!][meta.org]]  , then come back and do the steps above.
