CREATE UNLOGGED TABLE audit_event (
  bucket text,
  job text,
  audit_id text NOT NULL,
  stage text NOT NULL,
  event_verb text NOT NULL,
  request_uri text NOT NULL,
  operation_id text,
  event_level text,
  event_stage text,
  api_version text,
  useragent text,
  test_hit boolean,
  conf_test_hit boolean,
  event_user jsonb,
  object_namespace text,
  object_type text,
  object_group text,
  object_ver text,
  source_ips jsonb,
  annotations jsonb,
  request_object jsonb,
  response_object jsonb,
  response_status jsonb,
  stage_timestamp text,
  request_received_timestamp text,
  data jsonb NOT NULL
  -- id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- ingested_at timestamp DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX idx_audit_event_bucket        ON audit_event (bucket);
CREATE INDEX idx_audit_event_job  ON audit_event (job);
CREATE INDEX idx_audit_event_operation_id  ON audit_event(operation_id);
CREATE INDEX idx_audit_event_test_hit ON audit_event(test_hit);
CREATE INDEX idx_audit_event_conf_test_hit ON audit_event(conf_test_hit);
