# raiinbow.yaml
   

apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: hasura
  spec:
    type: ClusterIP
    clusterIP: None
    selector:
      io.apisnoop.graphql: hasura
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: postgres
  spec:
    selector:
      io.apisnoop.db: postgres
    ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: hasura
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          io.apisnoop.graphql: hasura
      spec:
        restartPolicy: Always
        containers:
        - name: hasura
          image: "raiinbow/hasura:2019-10-31-16-35"
          ports:
          - containerPort: 8080
          env:
          - name: HASURA_GRAPHQL_DATABASE_URL
            value: "postgres://apisnoop:s3cretsauc3@postgres:5432/apisnoop"
          - name: HASURA_GRAPHQL_ENABLE_CONSOLE
            value: "true"
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: postgres
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          io.apisnoop.db: postgres
      spec:
        restartPolicy: Always
        containers:
        - name: postgres
          image: "raiinbow/postgres:2019-10-31-16-35"
          ports:
          - containerPort: 5432
          livenessProbe:
            exec:
              command:
              - "pg_isready"
              - "-U"
              - "apisnoop"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
          - name: POSTGRES_DB
            value: apisnoop
          - name: POSTGRES_USER
            value: apisnoop
          - name: POSTGRES_PASSWORD
            value: s3cretsauc3
          - name: PGDATABASE
            value: apisnoop
          - name: PGUSER
            value: apisnoop
