#+TITLE: APISnoop WebApp Todo's
#+TODO: TODO(t) NEXT(n) WAITING(w) | DONE(d)

This document manages tasks and their progress.  New items are placed into the inbox, then organized into its relevant project.  There is always only one next item, that shows the next item we'll be working on.
* Inbox
** DONE Bring Back Latest Route
   CLOSED: [2020-07-06 Mon 11:11]
   We have routes for each release, zoomed into a level, category, and endpoint.
   e.g.
   : apisnoop.cncf.io/1.19.0/stable/core/createCoreV1NamespacedSecret
   In addition, there should be a 'latest' route, that always shows whatever is the most recent release.  This let's someone routinely check a url like:
   : apisnoop.cncf.io/latest/stable/network
   if they're wanting to track progress on just this section.
   
** NEXT Change header from '1.XX in Depth" to "1.XX Testing Coverage"
** TODO Write README for webapp
** TODO Transform Conformance-Progress to svelte page
** TODO Improve readability of conformance progress graphs
** TODO Add Reset Button to go back to original depth.
** TODO update favicon to apisnoop logo
** TODO Make 'switch release' button stand out more
* Projects
* Future/Maybe-Someday
** Keep text copy separate from code, so others can update it as they please.
   mainly with the about page
