#+TITLE: APISnoop WebApp Todo's
#+TODO: TODO(t) NEXT(n) WAITING(w) | DONE(d)

This document manages tasks and their progress.  New items are placed into the inbox, then organized into its relevant project.  There is always only one next item, that shows the next item we'll be working on.
* Inbox
** NEXT Bring Back Latest Route
   We have routes for each release, zoomed into a level, category, and endpoint.
   e.g.
   : apisnoop.cncf.io/1.19.0/stable/core/createCoreV1NamespacedSecret
   In addition, there should be a 'latest' route, that always shows whatever is the most recent release.  This let's someone routinely check a url like:
   : apisnoop.cncf.io/latest/stable/network
   if they're wanting to track progress on just this section.
** TODO Transform Conformance-Progress to svelte page
** TODO Improve readability of conformance progress graphs
** TODO Change header from '1.XX in Depth" to "1.XX Testing Coverage"
** TODO Add Reset Button to go back to original depth.
** TODO Write README for webapp
* Projects
* Future/Maybe-Someday
** Keep text copy separate from code, so others can update it as they please.
   mainly with the about page
