#+TITLE: APISnoop WebApp Todo's
#+TODO: TODO(t) NEXT(n) WAITING(w) | DONE(d)

This document manages tasks and their progress.  New items are placed into the inbox, then organized into its relevant project.  There is always only one next item, that shows the next item we'll be working on.
* Inbox
** DONE Bring Back Latest Route
   CLOSED: [2020-07-06 Mon 11:11]
   We have routes for each release, zoomed into a level, category, and endpoint.
   e.g.
   : apisnoop.cncf.io/1.19.0/stable/core/createCoreV1NamespacedSecret
   In addition, there should be a 'latest' route, that always shows whatever is the most recent release.  This let's someone routinely check a url like:
   : apisnoop.cncf.io/latest/stable/network
   if they're wanting to track progress on just this section.
   
** DONE Change header from '1.XX in Depth" to "1.XX Testing Coverage"
   CLOSED: [2020-07-06 Mon 11:17]
** DONE Write README for webapp
   CLOSED: [2020-07-06 Mon 11:26]
** DONE Transform Conformance-Progress to svelte page
   CLOSED: [2020-07-06 Mon 17:33]
** DONE Improve readability of conformance progress graphs
   CLOSED: [2020-07-06 Mon 18:13]
   - larger labels for x,y axes
   - larger font size for legends
   - positive/negative x-axis on still untested chart, to better show the ratio of tested to still untested
** DONE update favicon to apisnoop logo
   CLOSED: [2020-07-20 Mon 16:31]
** TODO Add Reset Button to go back to original depth.
** TODO Make 'switch release' button stand out more
** TODO move page switching logic out of sunburst component
   Doesn't smell right.  The component can bring forward a new page request, that contains the path of the page we'd want to go to, but I think this should be handled at the route level, and not the component level.  This makes our logic in the component focus only on display and click events within the component.
* Projects
* Future/Maybe-Someday
** Keep text copy separate from code, so others can update it as they please.
   mainly with the about page
