#+TITLE: Checking Conformance Progress with Triage Party
#+AUTHOR: Stephen Heywood

* [[http://triageparty.apisnoop.io/][triageparty.apisnoop.io]]

While the Conformance group has a [[https://github.com/orgs/kubernetes/projects/9][project board]], at a glance it's hard to see what's recently changed or in need of unblocking.
Using [[https://github.com/google/triage-party][Triage Party]] may facilitate an easier way for anyone to review the current progress of the project and how to locate an area where they can contribute to.

#+begin_quote
Triage Party is a tool for triaging incoming GitHub issues for large open-source projects, built with the GitHub API.
#+end_quote

Please checkout [[http://triageparty.apisnoop.io/][triageparty.apisnoop.io]] and feel free to provide any feedback via an issue or [[https://app.slack.com/client/T09NY5SBT/C78F00H99][#k8s-conformance]] on [[https://kubernetes.slack.com/][Slack]].

* What's been customized?

To scope the usage of Triage Party for =area/conformance= the default [[https://github.com/google/triage-party/blob/master/config/examples/kubernetes.yaml][YAML for Kubernetes]] has a few configurations changes.

** Update filters

All filters include a label for area/conformance

#+begin_src yaml
filters:
      - label: "area/conformance"
#+end_src

** Lifecycle issues

Due to the age of =lifecycle= issues the current thought was at they shouldn't be part of "Daily Triage".
They can been found in "Quarterly Scrub" under "Issue: Backlog"

#+begin_src yaml
  issue-backlog:
    name: "Issue: Backlog"
    type: issue
    filters:
      - label: "area/conformance"
      - label: "lifecycle/(stale|frozen|rotten)"
#+end_src

* Configuration

The collections and rules used by Triage Party are located in [[file:k8s-area-conformance-triage-party.yaml][k8s-area-conformance-triage-party.yaml]]

