#+title: Resources

* Introduction
This document outlines the resources needed to run or host APISnoop and where they live.
* The website
Our website lives at apisnoop.cncf.io.  This shows the static pages created in ~/apps/web~.
** Hosting
The site is hosted on [[https://netlify.com]], by the organisation "APISnoop Enterprise": https://app.netlify.com/teams/apisnoop

This organisation was created, and funded, by CNCF.
*** build settings
- Runtime ::  Not set
- Base directory :: apps/web/
- Build command :: npm install && npm run build
- Publish directory :: apps/web/public
- Deploy log :: visibility Logs are public
- Build status :: Active
*** Site's data source
The website renders the graphs from the json that lives in this repo at
~/resources/coverage~. It stores the url for this repo at ~/apps/web/src/lib/constants.js~. If we decide to host the code elsewhere, we will want to update this constants file.
** Domain
Apisnoop is a subdomain of cncf.io, and so the domain is owned and operated by cncf.




* Our images
When we use apisnoop for work (e.g. running snoopdb to generate reports or assist in writing tests), we most often run it from an image.  For example, when apisnoop is deployed in a cluster, it is deployed with the helm charts in ~/charts~ which point to the most recent images for each part.

These images are created and hosted by gcr within the org ~k8s-staging-apisnoop~.  All images are available here:
- snoopdb :: https://console.cloud.google.com/gcr/images/k8s-staging-apisnoop/global/snoopdb?project=k8s-staging-apisnoop
- auditlogger :: https://console.cloud.google.com/gcr/images/k8s-staging-apisnoop/global/auditlogger?project=k8s-staging-apisnoop
- webapp :: https://console.cloud.google.com/gcr/images/k8s-staging-apisnoop/global/webapp?project=k8s-staging-apisnoop

  I am not certain the owner of this org, I believe it was created and maintained by hh.
** How they are built
  The workflow for building and hosting the images are defined in a ~cloudbuild.yaml~ file within each of the app services (.e.g ~/apps/snoopdb/cloudbuild.yaml~)
* Updating our coverage
We periodically update the jsons in ~resources/coverage~ with the latest test runs from the kubernetes prow.  We also will update the necessary code for whenever there is a new release of kubernetes.  All of this is handled in github actions, as defined in our ~.github~ folder.
* Anything else?
I believe this is all parts necessary for running and hosting apisnoop!
