#+TITLE: Updating APISnoop upon a new release

APISnoop is intended to have test coverage for the latest working release of Kubernetes, plus earlier releases going back to 1.15.  The /working release/ is the one after the official /current stable/ release. So if the /current stable/ release is ~1.19.0~, then the /working release/ is ~1.20.0~.

Snoopdb determines its /working release/ by looking at [[https://github.com/cncf/apisnoop/blob/master/resources/coverage/releases.yaml][cncf/apisnoop/resources/coverage/releases.yaml]] and grabbing the top version from this list.

When Kubernetes releases a new /current stable/ version, this yaml file needs to be updated so that our db knows what the new working release should be.  Currently, this is done manually.

e.g. after ~1.20.0~ is released  as the current stable version, then our releases.yaml should be changed to look like this:

#+BEGIN_EXAMPLE yaml
---
- 1.21.0
- 1.20.0
- 1.19.0
- 1.18.0
- 1.17.0
- 1.16.0
- 1.15.0
#+END_EXAMPLE

Push these changes, and the next time snoopdb generates coverage info, it will generate coverage for this new version.
