#+TITLE: Test Writing Tutorial Notes

* Purpose                                           :test:writing:k8s:ii:raw:
Raw notes from a session run with Caleb and Zach about using apisnoop for test-writing.
Note, still very RAW, just getting information out of my head, any edits, updates welcome

* Setting up a test enviroment in a packet box via Windows:
- Launch Pagant and Click "Add key"
- Launch Packet box by stating PuTTY
- Select profile in PuTTY ie. UseriiNZ and click load, Terminal window will launch
- Launch Kubemacs by typing ./Kubemacs.sh
  - Tip: type ./k + TAB to auto complete
- Prompt will apear on the screen: "Are you happy with using the configuration above" Check Config and press ENTER
  - If changes is needed update the Kubemacs.env file

* Tip: Trouble launching Kubemacs:
    - type $ Docker ls to list open containers
    - open containers can be stopped by typing: $ docker stop $(docker ps -a -q)
    - open containers can be removed by typing: $ docker rm $(docker ps -a -q)

- Once Kubemacs have launched the terminal window will display: Root@user:/#
- Type: exit + ENTER, Spacemacs will load and open the user's flow.org file. Follow prompts for loading the file.

* Entering the test writing enviroment:
- In spacemacs type: SPACE f f to open a file
- Go to home/ii/apisnoop and open test-writing.org
- Once the file is open go to Ingress configuration and open sub tree with TAB
- Go to Update YOUPIP.xip.io and open code block wit TAB
  To run the shell script, with in the code block type in command mode: ,, to run the block. This will update your IP Address.

* Next steps is to bring up Tilt:
- Type Ctrl b c to open a new bash session.
- Type cd apisnoop + ENTER
- Type: tilt up --host 0.0.0.0 + ENTER
- Return to the emacsclient to start test writing

* Test writing:
- Open a new buffer: SPACE b N n
- Safe the file with a draft test name of your choice in /apisnoop/tickets/k8s/yourfilename.org
- Type f f and type insert-mock-template, select the file and press ENTER.
- The mock ticket template will open in the file.
- You are ready to start test writing!!

* Test writing explained:
Must read documents before test writing:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md

* Subimiting an Issue:
Once the test is completed it must be exported to the https://github.com/kubernetes/kubernetes repo in Github Flavored Markdown.
- Type , e e g G
- This will open the test file in temp buffer in Github Flavored Markdow file format.
- Select and copy all the text with:
  - gg
  - SHIFT G
  - SHIFT V
  - y
- Go to  https://github.com/kubernetes/kubernetes in you web browser
- CLick on Issues and New Issue
- At the bottom of the page select "Don’t see your issue here? Open a blank issue."
- In the blank template "write" section paste the mark down test text.
- In the heading box add an appropriate heading and add the number of end point coverage increased.
- If all entries are done, click "Submit new issue"
- To place the new ticket on the Kubernetes project board go to https://github.com/orgs/kubernetes/projects/9
- CLick add cards, find the new issue and drag it to the column "To Triage"
- Go to the internal ii Dashboard https://github.com/cncf/apisnoop/projects/28 create a new card under TestIssue-Created.
- In the note add the test name, hyperlink to the org file and number of end points. ie.  [TestName.org](https://github.com/cncf/apisnoop/blob/master/tickets/k8s/TestName.org) (+2)
The CNCF Project 9 ticket will be move in the Conformance meeting. The ii Project 28 ticket will be move by ii as the task progress. The .org file must the update with links to other files.










Tips:
- Tips: Get help in Packet box terminal type: =curl cht.sh/= Followed by the help topic.
- In the Box, launch a new window with =Clt b, c=
- Move to a open window +Clt b, followed by window number in the Kubmacs bar.
- Select text in terminal window in Windows enviroment - SHIFT + Click & drag
