#+TITLE: APISnoop Update

* Our Mission
“What are the fields related to PodSpec?”
* Why is this important?
  - isolating these fields will help us determine their coverage.
  - this provides a different view of coverage than the current one based on endpoint.
  - Coverage based on Podspec fields helps us figure out how well _behaviors_ of kubernetes are tested.
* Our Methods
  - Populate a postgres db with raw swagger.json’s and raw audit_events
  - Construct a recursive view that walks through the swagger definitions, tracing the path from spec to spec.
  - Extend the view for each field to show if it’s alpha/beta, feature-gated, or deprecated.
  - More details, and sample queries, can be found at https://apisnoop.sharing.io/2019-08-19_update.html
* Points of Interest
  - Calculating our extended view was harder than anticipated due to lack of standard on how these fields should be marked.
  - There are some stable, GA podspec fields without conformance tests.
  - Unsure which method we should use to walk through this swagger: munging text files or working with yaml.
* Next Steps
  - Connect this work to our existing work in audit events to calculate coverage field by field.
  - Get feedback on recommendations outlined in our report.
  - PR’s to help with the documentation and standardization of the alpha/beta, and feature-gated fields.


